
project_id = "dqzzkycxafylvjghppst"

[events-management]
verify_jwt = true

[payment-processing]
verify_jwt = false 

[generate-eco-tips]
verify_jwt = false

[analyze-recycling-impact]
verify_jwt = false
